image: gcr.io/single-quanta-422507-f2/jsvill-fullstack:latest

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 3Gi
  grafana:
    grafana.ini:
      server:
        domain: 35.221.202.91
    service:
      type: LoadBalancer
      loadBalancerIP: 35.221.202.91
    adminUser: sean
    adminPassword: '1730'
    persistence:
      type: pvc
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 3Gi
      finalizers:
        - kubernetes.io/pvc-protection

#loki:
#  enabled: true
#  schemaConfig:
#    configs:
#      - from: 2024-05-07
#        store: boltdb-shipper
#        object_store: filesystem
#        schema: v11
#        index:
#          prefix: index_
#          period: 24h
#  minio:
#    enabled: false
#  loki:
#    auth_enabled: false
#  write:
#    persistence:
#      size: 3Gi
#  read:
#    persistence:
#      size: 3Gi
#  backend:
#    persistence:
#      size: 3Gi
#  monitoring:
#    selfMonitoring:
#      grafanaAgent:
#        installOperator: false
#
promtail:
  scrape_configs:
    - job_name: jsvill-logs
      static_configs:
        - targets:
            - localhost
          labels:
            job: jsvill-helm
            __path__: /var/log/contains/*.log
