apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: jsvill-charts
    repo: https://sean-creative.github.io/JSVILL
    version: 0.0.82
    releaseName: jsvill-helm
    namespace: default

  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 56.2.0
    valuesFile: values-prometheus.yaml
    releaseName: prometheus
    namespace: monitoring

  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 5.41.0
    valuesFile: values-loki.yaml
    releaseName: loki
    namespace: monitoring

  - name: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.15.4
    valuesFile: values-promtail.yaml
    releaseName: promtail
    namespace: monitoring
