apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: jsvill-charts
    repo: https://sean-creative.github.io/JSVILL
    version: 0.0.68
    releaseName: jsvill
    namespace: default

  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 56.2.0
    releaseName: prometheus
    namespace: monitoring
    valuesFile: values-prometheus.yaml

  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 5.41.8
    releaseName: loki
    namespace: monitoring
    valuesFile: values-loki.yaml

  - name: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.15.4
    releaseName: promtail
    namespace: monitoring
    valuesFile: values-promtail.yaml