prometheus: 
  prometheusSpec: 
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 3Gi
grafana:
  grafana.ini:
    server:
#      그라파나 주소
      domain: 35.221.202.91
  service:
    type: LoadBalancer
    loadBalancerIP: 35.221.202.91
  adminUser: sean
  adminPassword: '1730'
  persistence:
    type: pvc
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 3Gi
    finalizers:
      - kubernetes.io/pvc-protection