prometheus: 
  prometheusSpec: 
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 3Gi
    
grafana:
  grafana.ini:
    smtp:
      enabled: true
      skip_verify: true
      host: smtp.gmail.com:587
      existingSecret: "my-grafana-smtp-secret"      
      userKey: "user"
      passwordKey: "password"
  replicas: 1
  service:
    type: LoadBalancer
    loadBalancerIP: 34.80.56.98
  adminUser: sean
  adminPassword: '1730'
  persistence:
    type: pvc
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 3Gi
    finalizers:
      - kubernetes.io/pvc-protection
