minio:
  enabled: true
  size: 3Gi
loki:
  auth_enabled: false
write:
  persistence:
    size: 3Gi
read:
  persistence:
    size: 3Gi
backend:
  persistence:
    size: 3Gi


monitoring:
  selfMonitoring:
    grafanaAgent:
      installOperator: false


      
