#clients:
#- url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: jsvill-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: jsvill-helm
      __path__: /var/log/contains/*.log
