prometheus: 
  prometheusSpec: 
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 3Gi
grafana:
  grafana.ini:
#    여기서 grafana Settings 내용을 적어야함 ex) domain
  service:
    type: LoadBalancer
    loadBalancerIP: 34.80.56.98
  adminUser: sean
  adminPassword: '1730'
  persistence:
    type: pvc
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 3Gi
    finalizers:
      - kubernetes.io/pvc-protection
