apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: jsvill
    repo: https://sean-creative.github.io/JSVILL
    version: 0.0.2
    releaseName: jsvill
    namespace: default
    valuesFile: values.yaml