apiVersion: v1
kind: Service
metadata:
  name: jsvill-helm
  labels:
     app: jsvill-helm 
  namespace: default
spec:
  selector:
    app: jsvill-helm 
  ports:
    - name: http
      protocol: TCP  
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 34.81.199.207