apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-3
      broker: "3"
  template:
    metadata:
      labels:
        app: kafka-broker-3
        broker: "3"
    spec:
      containers:
        - name: kafka-broker-3
          image: confluentinc/cp-kafka:5.5.1
          ports:
            - containerPort: 9094
          env:
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-1:32181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-broker-3:9094"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_NUM_PARTITIONS
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-3
spec:
  type: ClusterIP
  ports:
    - port: 9094
      targetPort: 9094
  selector:
    app: kafka-broker-3
    broker: "3"
