apiVersion: v2
name: loki
description: A Helm chart for Loki in Kubernetes
version: 5.41.8
appVersion: "1.0"

# Default values for loki.
# values from values-loki.yaml
minio:
  enabled: true
  size: 3Gi
loki:
  auth_enabled: false
write:
  persistence:
    size: 3Gi
read:
  persistence:
    size: 3Gi
backend:
  persistence:
    size: 3Gi

monitoring:
  selfMonitoring:
    grafanaAgent:
      installOperator: false
