apiVersion: v2
name: prometheus
description: A Helm chart for Prometheus Stack in Kubernetes
version: 56.2.0
appVersion: "1.0"


# Default values for kube-prometheus-stack.
# values from values-prometheus.yaml
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 3Gi
grafana:
  grafana.ini:
    server:
      domain: 35.221.202.91
  service:
    type: LoadBalancer
    loadBalancerIP: 35.221.202.91
  adminUser: sean
  adminPassword: '1730'
  persistence:
    type: pvc
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 3Gi
    finalizers:
      - kubernetes.io/pvc-protection
