apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-redis
  template:
    metadata:
      labels:
        app: session-redis
    spec:
      containers:
        - name: session-redis
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: session-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: session-redis