apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      containers:
        - name: zookeeper-1
          image: confluentinc/cp-zookeeper:5.5.1
          ports:
            - containerPort: 32181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "32181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1
spec:
  ports:
    - port: 32181
      targetPort: 32181
  selector:
    app: zookeeper-1
