name: Release Charts

on:
  push:
    branches:
      - main
#    paths:
#      - 'charts/**'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.bump-version.outputs.new-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "ksw6125000@naver.com"
          git config --local user.name "Sean-creative"

      - name: Bump chart version
        id: bump-version
        run: |
          CHART_DIR=charts/jsvill-chart
          VERSION=$(grep 'version:' $CHART_DIR/Chart.yaml | awk '{print $2}')
          NEW_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          sed -i "s/version: $VERSION/version: $NEW_VERSION/" $CHART_DIR/Chart.yaml
          echo "::set-output name=new-version::$NEW_VERSION"
          git add $CHART_DIR/Chart.yaml
          git commit -m "Bump chart version to $NEW_VERSION"
          git push origin HEAD

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"

  update-kustomization:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Check directory and file
        run: |
          pwd
          ls -l
          cd kustomize
          pwd
          ls -l


      - name: Update kustomization version
        run: |
          cd kustomize
          NEW_VERSION=${{ needs.release.outputs.new-version }}
          sed -i "s/version: .*/version: $NEW_VERSION/" kustomization.yaml
          git add kustomization.yaml
          git commit -m "Update kustomization version to $NEW_VERSION"
          git push origin HEAD
